server:
  port: ${PORT:8092}

spring:
  application:
    name: vaccineAplications
  r2dbc:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    pool:
      enabled: true
      initial-size: 2
      max-size: 10
      max-idle-time: 30s
      validation-query: SELECT 1
      acquire-retry: 3
      acquire-retry-delay: 5s
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI}
          jwk-set-uri: ${JWT_JWK_SET_URI}

ciclodevida:
  api:
    url: ${CICLODEVIDA_API_URL}
